;;; drop-frame-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from drop-frame.el

(autoload 'drop-frame--create "drop-frame" "\
Create a new drop frame with the given parameters

(fn NAME SETUP-FNS &optional FRAME-PARAMS)")
(register-definition-prefixes "drop-frame" '("drop-frame--"))

;;; End of scraped data

(provide 'drop-frame-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; drop-frame-autoloads.el ends here
